version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  mongo:
    image: mongo:latest

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim

  api:
    image: ${REGISTRY:-cmmrc}/api:${TAG:-latest}
    build:
      context: ./src/http-api
      dockerfile: Dockerfile
    depends_on:
      - redis

  api-dapr:
    image: 'daprio/daprd:latest'
    network_mode: 'service:api'
    depends_on:
      - api
  
  identity:
   image: ${REGISTRY:-cmmrc}/identity:${TAG:-latest}
   build:
    context: ./src/auth-server
    dockerfile: Dockerfile

  functions:
    image: ${REGISTRY:-cmmrc}/functions:${TAG:-latest}
    build:
      context: ./src/functions
      dockerfile: Dockerfile

  functions-dapr:
    image: 'daprio/daprd:latest'
    network_mode: 'service:functions'
    depends_on:
      - functions
  
  react:
    image: ${REGISTRY:-cmmrc}/react:${TAG:-latest}
    build:
      context: ./src/react-client

  web:
    image: ${REGISTRY:-cmmrc}/web:${TAG:-latest}
    build:
      context: ./src/web-client
      dockerfile: Dockerfile

  web-dapr:
    image: 'daprio/daprd:latest'
    network_mode: 'service:web'
    depends_on:
      - web
  
  gateway:
    image: ${REGISTRY:-cmmrc}/gateway:${TAG:-latest}
    build:
      context: ./src/gateway
      dockerfile: Dockerfile

  gateway-dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:gateway"
    depends_on:
      - gateway
  
  # webstatus:
  #   image: xabarilcoding/healthchecksui:5.0.0

  dapr-placement:
    image: 'daprio/dapr:latest'