version: '3.4'

services:

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  gateway:
    environment:
      - ENVOY_CATALOG_API_ADDRESS=catalog-api
      - ENVOY_CATALOG_API_PORT=80
      - ENVOY_ORDERING_API_ADDRESS=ordering-api
      - ENVOY_ORDERING_API_PORT=80
    ports:
      - "5202:80"
      - "15202:8001"
      - "50008:50001"
  
  gateway-dapr:
    command: ["./daprd",
      "-app-id", "gateway",
      "-app-port", "80",
    ]