version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  mongo:
    image: mongo:latest

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim

  api:
    image: ${REGISTRY:-cmmrc}/api:${TAG:-latest}
    build:
      context: ./src
      dockerfile: http-api/Dockerfile
    depends_on:
      - redis

  api-dapr:
    image: 'daprio/daprd:latest'
    network_mode: 'service:api'
    depends_on:
      - api
  
  identity:
   image: ${REGISTRY:-cmmrc}/identity:${TAG:-latest}
   build:
    context: ./src
    dockerfile: auth-server/Dockerfile

  web:
    image: ${REGISTRY:-cmmrc}/web:${TAG:-latest}
    build:
      context: ./src
      dockerfile: web-client/Dockerfile

  web-dapr:
    image: 'daprio/daprd:latest'
    command: [
        './daprd',
        '-app-id',
        'web',
        '-app-port',
        '5002',
        '-dapr-http-port',
        '3502',
        '-placement-host-address',
        'placement:50010',
      ]
    network_mode: 'service:web'
    depends_on:
      - web
  
  gateway:
    image: ${REGISTRY:-cmmrc}/gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: src/gateway/Dockerfile

  gateway-dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:gateway"
    depends_on:
      - gateway
  
  # webstatus:
  #   image: xabarilcoding/healthchecksui:5.0.0

  dapr-placement:
    image: 'daprio/dapr:latest'