apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cmmrc-secretstore
  namespace: cmmrc
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: ./components/cmmrc-secrets.json
  - name: nestedSeparator
    value: "."
